name: Bot Service

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
      GITHUB_WORKSPACE: /home/ec2-user
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Copy Config
        run: cp ~/config/.env $GITHUB_WORKSPACE/.env
      - name: Run server script
        run: pm2 start index
        